// <auto-generated />
namespace OOS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041745426_edit-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
